dist: trusty
sudo: false

language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "SJKIK4dxBd3b5b1RcQ5TLpRknXYcBcMlW1NQmsca2gsRZqB3TanEGgqT7s/GzELQ+7/6L9P2EOm+uBXysLHifLUMPEB2Z3ytOZVGvVn/RF5eHzwsepzBM1hC1Iq42Nhl21AOruPs0rlo/eMLmWw/4hbcVA05V05SSRs0rDwGSOQMyLtJkjH8C9zd32RMuzEXFrE0xZAqRwvZ5y3TPwUTaTQ+wXMXUEtYVBCLc98EeQGfcN8EBUu9L1cVQ6ksaU5+JH1SyEcE6Weg9ah/cPIUpxwR1SNVz6I02rd47ZdFIg1XWUorNStEvIpbkHBZp6T9VM0Pd/POcAY1zCHalYxRfUdQhnNmXlRJIzxPPL6fhD7ixBbzNPP5SvvbVliLI+YYIZxVIhVz9fjI3NDBDxFNJMLFnSrSTojhBrkiA6fSS7ACQwtEVWrk3qFso+HYvLLEkYHtUhkC7IOu3ZFEcc6B5vs7wBQwZmlFzpqtxkmTQB7vksVnF7wO7jtfMJR7yYSnF2fLbQVkUfNdqGLfdUs3ViMDkWr225n8dOKs6kt8HXY++JT2AqGeGOEE0XxNz1ZyuZ0YX1Gx0XDXYWXSM9pCOxfg/mU536yenM9i1N/oTE+MHw76/IIW5h5Le19+J/WU4K+TMhmhvnCDqSXo3fPF11pGtwOOmf02GfvNVNpMCKI="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete